### ISSUE TITLE
Vidya trivia during streams/speedruns

### ISSUE THREAD

**Issue by wherewedroppinboys** [Marenthyu/NepBot#60]
Looks like a bunch of people thought this was a neat idea too so I'm throwing it into an issue here:

As an example to sort of outline what I mean by this, there's an addon in WoW that lets people play what's basically trivial pursuit in raid chat/guild chat/etc. Point reward optional but 10 points or whatever every few minutes wouldn't inflate the economy super hard imho - the main appeal of this would be to encourage people to actively participate in chat during runs. I think this would encourage activity in chat and be overall a cool addition.

Perhaps sort trivia by category, so if someone is playing a Neptunia game, it'd ask questions about the whole series, or if they're playing Xenoblade, same deal, etc. so it stays relevant to the stream at hand - alternatively, a pool of random video game trivia would work too. As well, if someone is speedrunning, speedrun-related questions would work, etc etc

As far as answering the questions would go, I'm guessing a simple command like !answer <answer text> would work? I know nothing about coding lol

in the words of zfresh, "enkidu throwing more work at you" ;^)

**Comment by Honbuk** [comment]
Saw trivia bots in other channels in the past that worked in 90 to 120 second intervals and it worked really great. The chat became active, even with only a few viewer. I think streamer would greatly appreciate it.

**Comment by Marenthyu** [comment]
If we do this, i guess it's a no-brainer that this'll have to be toggleable by the streamer, but in general i like the idea.
As an incentive, we could make it so the system increases its rewards during an active bet, to prevent it from spilling too many points into the economy and in return encourage people to not just join>bet>leave.

**Comment by Dabomstew** [comment]
Reiterating what I said on Discord: great idea in spirit, but requires a solid team to maintain the question base to make it realistic. That is certainly not something we can expect of the current staff base.

**Comment by xorhash** [comment]
**This does not strike me as a good idea.**

To clear my credentials first: I used to moderate a trivia room on Pokémon Showdown! for a while and I was involved with the Trivia bot on Rizon.

# Points Rewards

**If trivia does yield a points reward, it will get gamed very fast**. Even if the points reward is minor, it will also lead to some heavy points skewing in smaller channels: If only one or two people are answering questions, they can farm the everloving hell out of it.

People are inevitably going to learn the questions. You cannot prevent people from making lists of questions and tons of memorization. You cannot differentiate effectively between a very good player – of which you are almost certainly going to get at least one – and one that is building a searchable database and just manually types the answer in.

If you do not give a points reward, the system may possibly be dead in the water. However, there's probably going to be a small following no matter what you do; see the next section.

# Questions

Coming up with good questions takes a lot of work. Unless you heavily **limit how often the trivia can be run across all channels**, the pool will be exhausted in the blink of an eye. Writing good questions is extremely hard, too, as any ambiguity raises the overall salt levels of people losing to a bad question rather than a lack of skill.

The obvious solution is to have a dedicated question maintainer team. However, most of the players **tend to get relatively serious relatively fast** and they thus become natural candidates for the question maintainer team, which will then in turn give them another advantage in the game itself beyond their memorization. Vice-versa, the people who don't want to play will also likely not want to maintain the questions.

Maintaining the questions will also **generate administrative overhead**, even if delegated to an entirely separate team: Because the game is still part of NepNepBot, at least someone of the existing staff team will have to oversee what the trivia team is doing. There will probably be a need for more code so that the trivia team can independently add or remove questions or alternatively a lot of prodding the existing team to make changes for the question maintainer team. This will also possibly create additional confusion about who is or isn't an admin and can or can't be contacted for what kind of inquiries. Et cetera, et cetera.

Furthermore, **if the questions are biased, so will the particpation be**. Unless you have a well-rounded set of questions, it'll become boring for people who are outside of the "know" of the people who write the questions. It's already generally fairly uninteresting to compete with the serious people as a casual player, further solidifying the effect of ending up with a small playerbase.

# Chat Climate

Trivia games tend to lead to a lot of salt because of a corner case: typos. You'll have to decide (or have a per-stream configuration setting, which means :more database bloat:) what to do about typos. Does your bot do automatic fuzzy matching against the answer, e.g. with Levenshtein distance calculations? If so, where are the thresholds for what lengths of answers?

People will get equally salty:

1. if they typoed but no typos are accepted, so somebody "slower" won, or
2. if they did not typo but typos are accepted, so somebody "sloppier" won.

Even then, there's still any number of reasons they could "unfairly" lose, such as lag, Twitch being bad at being a chat platform (which is surprisingly often), being on mobile, etc.

**This is a genuine salt mine**, which derails chat more than the trivia bot itself already does. And all of this comes in addition to the usual bot spam, too. Given there's been work to make the bot messages less spammy, this is a heavy step in the opposite direction. You already have had strongly worded anti-salt rules for the bet feature, but you'll seriously be looking at reasons to enforce this on trivia. That or I see many streamers turning the feature off because of this; and I highly suggest making it opt-in, rather than opt-out.

# Conclusion

For all these reasons outlined above, **I thus strongly urge the staff team to dismiss this idea**.

**Comment by Marenthyu** [comment]
I couldn't say it better (or as well), but it summarizes my thiughts well.

Thus, i close this issue until a good opposite point gets made.
